name: Setup IPM CLI

on:
    push:
        branches:
            - main
    workflow_dispatch: # This allows the workflow to be triggered manually

jobs:
  setup-ipm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Install IPM CLI
        shell: bash
        run: |
          curl -Lo ipm-cli.tar.gz "https://layer8storagetests.blob.core.windows.net/cli-dl/0.1.0/ipm-cli-0.1.0-linux-x64-full.tar.gz?sv=2023-01-03&st=2025-01-31T15%3A01%3A13Z&se=2025-03-07T15%3A01%3A00Z&sr=b&sp=r&sig=JwbhiZ1L0vGNq7AxKlfyFAC3HREceC35lS2JrNiOVoA%3D"
          tar -xzf ipm-cli.tar.gz 
          sudo mv ./ipm /usr/local/bin/ipm

      - name: Run IPM Status
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          pwd
          ls -lah
          ipm status --non-interactive --client-secrets ${{ secrets.IPM_SECRET }}

      - name: Run IPM Sync
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          pwd
          ls -lah
          ipm sync --non-interactive --client-secrets ${{ secrets.IPM_SECRET }}

      - name: Update package version
        run: |
          sudo apt-get install -y jq
          jq '.packages[0].version = "0.1.0"' ipmhub.json > temp.json && mv temp.json ipmhub.json
          cat ipmhub.json

      - name: Run IPM Sync
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          pwd
          ls -lah
          ipm sync --non-interactive --client-secrets ${{ secrets.IPM_SECRET }}